# Project information
site_name: MkDocs RSS Plugin
site_description: Documentation about the MkDocs RSS Plugin
site_author: Julien M. (Guts)
site_url: https://guts.github.io/mkdocs-rss-plugin/
copyright: 'Guts - In Geo Veritas'

# Repository
repo_name: 'guts/mkdocs-rss-plugin'
repo_url: 'https://github.com/guts/mkdocs-rss-plugin/'

use_directory_urls: true

plugins:
  - minify:
      minify_html: true
  - rss:
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
  - search

theme:
  name: united
  language: en

# Extensions to enhance markdown
markdown_extensions:
  - attr_list
  - codehilite
  - meta
  - pymdownx.emoji
  - pymdownx.snippets:
      base_path: '.'
      check_paths: true
  - toc:
      permalink: '#'


nav:
- "Home": 'index.md'
- 'configuration.md'
