# Project information
site_name: MkDocs RSS Plugin
site_description: Documentation about the MkDocs RSS Plugin
site_author: Julien M. <dev@ingeoveritas.com>
site_url: https://guts.github.io/mkdocs-rss-plugin/
copyright: "Guts - In Geo Veritas (MIT)"

# Repository
repo_name: guts/mkdocs-rss-plugin
repo_url: https://github.com/guts/mkdocs-rss-plugin/
edit_uri: blob/main/docs/

# Custom folder structure
docs_dir: "docs/"
use_directory_urls: true

# Extensions to enhance markdown
markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.snippets:
      base_path: "."
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: "#"

nav:
  - "Home": "index.md"
  - "Settings": "configuration.md"
  - "Changelog": "changelog.md"

plugins:
  - git-committers:
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_GIT_COMMITTERS, true]
      repository: guts/mkdocs-rss-plugin
      branch: main
      docs_path: docs/
      cache_dir:
        !ENV [
          MKDOCS_PLUGIN_GIT_COMMITTERS_CACHE_DIR,
          .cache/plugins/git-committers/,
        ]
  - git-revision-date-localized:
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_GIT_DATES, true]
      enable_creation_date: true
      fallback_to_build_date: true
      locale: en
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
  - privacy:
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_PRIVACY, true]
      cache_dir:
        !ENV [MKDOCS_PLUGIN_PRIVACY_EXTERNAL_CACHE_DIR, .cache/plugins/privacy]
  - rss:
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d %H:%M"
        default_timezone: "Europe/Paris"
        default_time: "22:00"
      abstract_chars_count: 160
      abstract_delimiter: <!-- more -->
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      match_path: ".*"
      pretty_print: false
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
  - search:
      lang: en
  - social:
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_SOCIAL, true]
      cache_dir: !ENV [MKDOCS_PLUGIN_SOCIAL_CACHE_DIR, .cache/plugins/social]
  - termynal

theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    code: Ubuntu Mono
    text: Ubuntu
  icon:
    edit: material/pencil
    logo: simple/rss
    view: material/eye
    tag:
      default: fontawesome/solid/tag
  language: en
  palette:
    accent: amber
    primary: deep orange
    scheme: default

watch:
  - CONTRIBUTING.md
  - README.md
